### ISSUE TITLE
Updating value from main process doesn't reflect on renderer

### ISSUE THREAD

**Issue by bradjin8** [saucesteals/electron-persist-secure#1]
Hi, 
I created the store in main process using `electron-persist-secure` package.
```js
export const createStore = () => {
  store = new Store({
    configName: Constants.appName,
    watch: true
  });
};
```

I need to update the data from main process and tried this

```js
  const key = 'data.path.key';
  let old = store.get(key);
  store.set(key, newValue);
```

Get/Set works fine, but changes doesn't updated automatically via redux-persist on renderer side.
Is there anyway to solve this?
Thank you.

**Comment by saucesteals** [comment]
Updating the store in the main process will never reflect on the redux store as the only time the store is hydrated from the main process is when it is initialized, after which it only calls `.set(...)` - which essentially overrides any changes you might have made in the main process

The redux store should always be driven by the renderer - meaning you should never update it on the main process. However, if you ever need to update the store with data that only the main process has, you should be calling the renderer from the main process via the window IPC for the renderer to then dispatch to the store's reducers.

For example:

### Main process
```ts
window.webContents.send("foo", fooData)
```

### Preload
```ts
const fooBridge = {
  onFoo: (
    listener: (event: IpcRendererEvent, data: FooData) => void
  ): (() => void) => {
    const channel = "foo";
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.off(channel, listener);
  },
};

contextBridge.exposeInMainWorld("foo", fooBridge);
```
### Renderer
```ts
const off = window.foo.onFoo((event, data) => {
      dispatch(fooAction(data));
});

// If you need to clean-up
// off()
```

**Comment by bradjin8** [comment]
Thank you for your kind response.
I got it
